// Fallback mock data for when GitHub API rate limit is hit
const FALLBACK_TRENDING_PROJECTS = [
  {
    id: '1',
    name: 'react',
    description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
    url: 'https://github.com/facebook/react',
    platform: 'github' as const,
    stars: 219000,
    forks: 46000,
    language: 'JavaScript',
    license: 'MIT',
    lastUpdated: new Date().toISOString(),
    downloadedCount: 1500000,
    avatarUrl: 'https://avatars.githubusercontent.com/u/69631?v=4',
    owner: 'facebook',
    defaultBranch: 'main',
    topics: ['react', 'javascript', 'frontend', 'ui'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'next.js',
    description: 'The React Framework for the Web',
    url: 'https://github.com/vercel/next.js',
    platform: 'github' as const,
    stars: 115000,
    forks: 25000,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: new Date().toISOString(),
    downloadedCount: 890000,
    avatarUrl: 'https://avatars.githubusercontent.com/u/14985020?v=4',
    owner: 'vercel',
    defaultBranch: 'canary',
    topics: ['nextjs', 'react', 'ssr', 'framework'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'typescript',
    description: 'TypeScript is a superset of JavaScript that compiles to clean JavaScript output.',
    url: 'https://github.com/microsoft/typescript',
    platform: 'github' as const,
    stars: 95000,
    forks: 12400,
    language: 'TypeScript',
    license: 'Apache-2.0',
    lastUpdated: new Date().toISOString(),
    downloadedCount: 750000,
    avatarUrl: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    owner: 'microsoft',
    defaultBranch: 'main',
    topics: ['typescript', 'language', 'javascript'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'vscode',
    description: 'Code editing. Redefined.',
    url: 'https://github.com/microsoft/vscode',
    platform: 'github' as const,
    stars: 156000,
    forks: 36000,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: new Date().toISOString(),
    downloadedCount: 2500000,
    avatarUrl: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    owner: 'microsoft',
    defaultBranch: 'main',
    topics: ['vscode', 'editor', 'ide', 'typescript'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'tensorflow',
    description: 'An Open Source Machine Learning Framework',
    url: 'https://github.com/tensorflow/tensorflow',
    platform: 'github' as const,
    stars: 178000,
    forks: 89000,
    language: 'Python',
    license: 'Apache-2.0',
    lastUpdated: new Date().toISOString(),
    downloadedCount: 3200000,
    avatarUrl: 'https://avatars.githubusercontent.com/u/15658638?v=4',
    owner: 'tensorflow',
    defaultBranch: 'master',
    topics: ['tensorflow', 'machine-learning', 'deep-learning', 'python'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'kubernetes',
    description: 'Production-Grade Container Scheduling and Management',
    url: 'https://github.com/kubernetes/kubernetes',
    platform: 'github' as const,
    stars: 104000,
    forks: 39000,
    language: 'Go',
    license: 'Apache-2.0',
    lastUpdated: new Date().toISOString(),
    downloadedCount: 1800000,
    avatarUrl: 'https://avatars.githubusercontent.com/u/13629408?v=4',
    owner: 'kubernetes',
    defaultBranch: 'master',
    topics: ['kubernetes', 'containers', 'devops', 'cloud-native'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'vue',
    description: 'This is the repo for Vue 3. For Vue 2, see https://github.com/vuejs/core.',
    url: 'https://github.com/vuejs/core',
    platform: 'github' as const,
    stars: 42000,
    forks: 7600,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: new Date().toISOString(),
    downloadedCount: 890000,
    avatarUrl: 'https://avatars.githubusercontent.com/u/6128107?v=4',
    owner: 'vuejs',
    defaultBranch: 'main',
    topics: ['vue', 'javascript', 'frontend', 'framework'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'python',
    description: 'The Python programming language',
    url: 'https://github.com/python/cpython',
    platform: 'github' as const,
    stars: 46000,
    forks: 24000,
    language: 'Python',
    license: 'Python-2.0',
    lastUpdated: new Date().toISOString(),
    downloadedCount: 2100000,
    avatarUrl: 'https://avatars.githubusercontent.com/u/1525981?v=4',
    owner: 'python',
    defaultBranch: 'main',
    topics: ['python', 'programming-language', 'interpreter'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

import { NextRequest, NextResponse } from 'next/server';
import { githubApi, GitHubRepository } from '@/lib/github';

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const dateRange = searchParams.get('dateRange') as 'daily' | 'weekly' | 'monthly' | null;
  const language = searchParams.get('language');
  const limit = Math.min(parseInt(searchParams.get('limit') || '20'), 50);

  try {
    const repos = await githubApi.getTrendingRepositories({
      dateRange: dateRange || 'weekly',
      language: language || undefined,
      limit,
    });

    const projects = repos.map((repo: GitHubRepository) => ({
      id: String(repo.id),
      name: repo.name,
      description: repo.description,
      url: repo.html_url,
      platform: 'github' as const,
      stars: repo.stargazers_count,
      forks: repo.forks_count,
      language: repo.language,
      license: repo.license?.name || null,
      lastUpdated: repo.updated_at,
      downloadedCount: 0,
      avatarUrl: repo.owner.avatar_url,
      owner: repo.owner.login,
      defaultBranch: repo.default_branch,
      topics: repo.topics || [],
      createdAt: repo.created_at,
      updatedAt: repo.updated_at,
    }));

    return NextResponse.json({ projects, total: projects.length });
  } catch (error) {
    console.error('GitHub API error, using fallback data:', error);
    // Return fallback data when API fails (rate limit, etc.)
    const fallbackProjects = FALLBACK_TRENDING_PROJECTS.slice(0, limit);
    return NextResponse.json({ projects: fallbackProjects, total: fallbackProjects.length, fallback: true });
  }
}
